### PR TITLE
Modifiable timeout and rsync check

### PR DESCRIPTION
**Pull request by Grouter**
* added timeout flag so user can define program time limit (-t/--timeout TIME) in seconds
* check for rsync command, if not present, regular cp will be used
* added rsync as optional dependency to README

### CODE REVIEW

**Comment by martinkonopka** [comment]
Tested it, works now without `rsync`.
I just noticed another problem, but only minor, that when `runs` directory does not exist, `mkdir` fails to create directory for the run:

```
mkdir: cannot create directory 'runs/src.c': No such file or directory
```

All tests then fail. If I create `runs` directory manually (not the `src.c` for source code), then it works. Can you add a check for the directory existence and create it if not after the compilation? Don't know if `mkdir` has different behavior in MinGW Bash, but this is covered in the PowerShell version.

**Comment by martinkonopka** [comment]
Thank you very much, merging it.

**Comment by Grouter** [comment]
Yeah, sorry about that... for some reason it stopped working. New commit fixed it. Also I added checking for tests/ folder just to be sure.

**Comment by martinkonopka** [comment]
Can you open a PR if that's all? The last commit wasn't included in the last PR.

**Comment by Grouter** [comment]
On it.

**Pull request merged**
